-- Supabase database schema for the CA voting app.
-- Run this in Supabase SQL Editor.

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  created_at timestamptz not null default now(),
  rule_1 char(16) not null,
  rule_2 char(16) not null,
  rule_3 char(16) not null,
  rule_4 char(16) not null,
  winner char(16) not null
);

-- Basic integrity checks.
alter table public.votes
  drop constraint if exists votes_rule_1_format;
alter table public.votes
  drop constraint if exists votes_rule_2_format;
alter table public.votes
  drop constraint if exists votes_rule_3_format;
alter table public.votes
  drop constraint if exists votes_rule_4_format;
alter table public.votes
  drop constraint if exists votes_winner_format;

alter table public.votes
  add constraint votes_rule_1_format check (rule_1 ~ '^[12]{16}$'),
  add constraint votes_rule_2_format check (rule_2 ~ '^[12]{16}$'),
  add constraint votes_rule_3_format check (rule_3 ~ '^[12]{16}$'),
  add constraint votes_rule_4_format check (rule_4 ~ '^[12]{16}$'),
  add constraint votes_winner_format check (winner ~ '^[12]{16}$');

-- Make querying by anonymous session fast.
create index if not exists votes_session_id_idx
  on public.votes(session_id);

create index if not exists votes_created_at_idx
  on public.votes(created_at);

create index if not exists votes_winner_idx
  on public.votes(winner);

-- Do NOT expose the table directly to anonymous browsers.
-- Votes should go through the Edge Function.
alter table public.votes enable row level security;

-- No anon SELECT/INSERT/UPDATE/DELETE policies are created intentionally.
